# Generated by Django 5.1.5 on 2026-05-19 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_translate_catalog_names"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="workoutsession",
            new_name="api_workout_user_id_3765b1_idx",
            old_name="api_workout_user_id_e9f565_idx",
        ),
    ]
