[project]
name = "web-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic==1.14.0",
    "django==5.1.5",
    "fastapi==0.115.6",
    "drf-spectacular>=0.29.0",
    "psycopg==3.2.12",
    "sqlalchemy==2.0.36",
    "djangorestframework>=3.16.1",
    "djangorestframework-simplejwt>=5.5.1",
    "python-dotenv>=1.2.2",
]
